### ISSUE TITLE
#2 Dashboard per rol

### ISSUE THREAD

**Issue by Dijckp** [sepkevw/barroc_intens#43]
Als medewerker wil ik na het inloggen het dashboard zien dat hoort bij mijn rol zodat ik meteen toegang heb tot de relevante informatie en functies.

Acceptatiecreteria:

Elke rol(Finance, Sales, Inkoop en Maintenance heeft een apart dashboard en tonen alleen informatie voor de toegewezen rol.

Na het inloggen wordt de medewerker automatisch naar het juiste dashboard geleid.

**Comment by animal-adj** [comment]
deze dashboards worden apart (niet hardcoded) gemaakt, het ticket is opgesplitst
